parameters:
    doctrine_mongodb.odm.document_manager.class: App\SyntheseBundle\Model\DocumentManager
    doctrine_mongodb.odm.class: App\SyntheseBundle\MongoDB\Registry
services:
#    synthese.example:
#        class: SyntheseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
